// Copyright (c) 2013-2026 xipki. All rights reserved.
// License Apache License 2.0

package org.xipki.ca.api.profile.ctrl;

import org.xipki.security.KeySpec;
import org.xipki.util.codec.Args;

import java.security.NoSuchAlgorithmException;

/**
 * Configuration how the keypair is generated by CA.
 *
 * @author Lijun Liao (xipki)
 *
 */
public class KeypairGenControl {

  public static final KeypairGenControl INHERIT_CA =
      new KeypairGenControl(true, false, null);

  public static final KeypairGenControl FORBIDDEN =
      new KeypairGenControl(false, true, null);

  private final boolean inheritCA;

  private final boolean forbidden;

  private final KeySpec keySpec;

  private KeypairGenControl(boolean inheritCA, boolean forbidden,
                            KeySpec keySpec) {
    this.inheritCA = inheritCA;
    this.forbidden = forbidden;
    this.keySpec = keySpec;
  }

  public KeypairGenControl(KeySpec keySepc) {
    this(false, false, Args.notNull(keySepc, "keySpec"));
  }

  public boolean isInheritCA() {
    return inheritCA;
  }

  public boolean isForbidden() {
    return forbidden;
  }

  public KeySpec getKeySpec() {
    return keySpec;
  }

  public String text() {
    return inheritCA ? "InheritCA"
        : forbidden ? "Forbidden"
        : keySpec.getText();
  }

  public static KeypairGenControl valueOf(String name)
      throws NoSuchAlgorithmException {
    return "InheritCA".equalsIgnoreCase(name) ? INHERIT_CA
        : "Forbidden".equalsIgnoreCase(name) ? FORBIDDEN
        : new KeypairGenControl(KeySpec.ofKeySpec(name));
  }

}
