// Copyright (c) 2013-2025 xipki. All rights reserved.
// License Apache License 2.0

package org.xipki.ca.certprofile.xijsonv1.conf;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.xipki.ca.api.profile.ctrl.KeypairGenControl;
import org.xipki.ca.certprofile.xijsonv1.conf.type.DescribableOid;
import org.xipki.security.KeySpec;
import org.xipki.security.OIDs;
import org.xipki.security.util.EcCurveEnum;
import org.xipki.util.codec.CodecException;
import org.xipki.util.codec.json.JsonMap;
import org.xipki.util.extra.exception.CertprofileException;

import java.util.Map;

/**
 * Configuration how the keypair is generated by CA.
 *
 * @author Lijun Liao (xipki)
 * @since 2.0.0
 */

public class V1KeypairGenerationType {

  public static final String PARAM_keysize = "keysize";

  public static final String PARAM_curve = "curve";

  private Boolean inheritCA;

  private Boolean forbidden;

  private DescribableOid algorithm;

  /**
   * The following properties will be evaluated.
   *
   * <ul>
   *   <li>For RSA key
   *     <ul>
   *       <li>keysize (required)</li>
   *     </ul>
   *   </li>
   *   <li>For EC key
   *     <ul>
   *       <li>curve (required)</li>
   *     </ul>
   *   </li>
   *   <li>For DSA key
   *     <ul>
   *       <li>plength (required)</li>
   *       <li>qlength (optional)</li>
   *     </ul>
   *   </li>
   *   <li>For Edwards and Montgomery key
   *     <ul>
   *       <li>no parameter</li>
   *     </ul>
   *   </li>
   * </ul>
   */
  private Map<String, String> parameters;

  public KeypairGenControl toV2() throws CertprofileException {
    if (isSetAndTrue(inheritCA)) {
      return KeypairGenControl.INHERIT_CA;
    } else if (isSetAndTrue(forbidden)) {
      return KeypairGenControl.FORBIDDEN;
    }

    ASN1ObjectIdentifier oid = algorithm.oid();

    if (OIDs.Algo.id_rsaEncryption.equals(oid)) {
      String str = (parameters == null) ? null : parameters.get(PARAM_keysize);
      if (str == null) {
        return new KeypairGenControl(KeySpec.RSA2048);
      }

      int keysize = Integer.parseInt(str);
      KeySpec keySpec = KeySpec.ofRSA(keysize);
      if (keySpec == null) {
        throw new CertprofileException("unsupported RSA key size " + keysize);
      }
      return new KeypairGenControl(keySpec);
    } else if (OIDs.Algo.id_ecPublicKey.equals(oid)) {
      String str = (parameters == null) ? null : parameters.get(PARAM_curve);
      if (str == null) {
        return new KeypairGenControl(KeySpec.SECP256R1);
      }

      EcCurveEnum curveEnum = EcCurveEnum.ofOid(new ASN1ObjectIdentifier(str));
      if (curveEnum == null) {
        throw new CertprofileException("unsupported EC curve " + str);
      }
      KeySpec keySpec = KeySpec.ofEcCurve(curveEnum);
      return new KeypairGenControl(keySpec);
    } else {
      KeySpec keySpec =
            OIDs.Curve.id_ED25519.equals(oid)  ? KeySpec.ED25519
          : OIDs.Curve.id_ED448.equals(oid)    ? KeySpec.ED448
          : OIDs.Curve.id_X25519.equals(oid)   ? KeySpec.X25519
          : OIDs.Curve.id_X448.equals(oid)     ? KeySpec.X448
          : OIDs.Algo.id_ml_dsa_44.equals(oid) ? KeySpec.MLDSA44
          : OIDs.Algo.id_ml_dsa_65.equals(oid) ? KeySpec.MLDSA65
          : OIDs.Algo.id_ml_dsa_87.equals(oid) ? KeySpec.MLDSA87
          : OIDs.Algo.id_ml_kem_512.equals(oid)  ? KeySpec.MLKEM512
          : OIDs.Algo.id_ml_kem_768.equals(oid)  ? KeySpec.MLKEM768
          : OIDs.Algo.id_ml_kem_1024.equals(oid) ? KeySpec.MLKEM1024
          : null;

      if (keySpec == null) {
        throw new CertprofileException("unknown key algorithm " + oid.getId());
      }

      return new KeypairGenControl(keySpec);
    }
  }

  public static V1KeypairGenerationType parse(JsonMap json)
      throws CodecException {
    V1KeypairGenerationType ret = new V1KeypairGenerationType();
    ret.inheritCA = json.getBool("inheritCA");
    ret.forbidden = json.getBool("forbidden");
    ret.algorithm = DescribableOid.parse(json, "algorithm");
    ret.parameters = json.getStringMap("parameters");
    return ret;
  }

  private static boolean isSetAndTrue(Boolean b) {
    if (b == null) {
      return false;
    }
    return b;
  }

  public enum KeyType {
    RSA, EC, DSA, ED25519, ED448, X25519, X448, MLDSA, MLKEM
  }

}
