/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xipki_pkcs11_wrapper_jni_Libpkcs11 */

#ifndef _Included_org_xipki_pkcs11_wrapper_jni_Libpkcs11
#define _Included_org_xipki_pkcs11_wrapper_jni_Libpkcs11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    getArch
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_getArch
  (JNIEnv *, jclass);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    initializeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_initializeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    closeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_closeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    initModule
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_initModule
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    closeModule
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_closeModule
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    getVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_getVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_xipki_pkcs11_wrapper_jni_Libpkcs11
 * Method:    query
 * Signature: (I[BIJJJI[B[BJ[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_xipki_pkcs11_wrapper_jni_Libpkcs11_query
  (JNIEnv *, jclass, jint, jbyteArray, jint, jlong, jlong, jlong, jint,
   jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
