# Register the FileHandler and ConsoleHandler
handlers = org.apache.juli.FileHandler

############################################################
# Handler Configuration
############################################################

# Use 'org.apache.juli.FileHandler' instead of the standard Java FileHandler.
# This version is aware of Tomcat's environment and allows %s for context name.
org.apache.juli.FileHandler.level = INFO
org.apache.juli.FileHandler.directory = ${catalina.base}/logs
org.apache.juli.FileHandler.prefix = ${logfile}.
org.apache.juli.FileHandler.suffix = .log
org.apache.juli.FileHandler.formatter = java.util.logging.SimpleFormatter

## rotating
org.apache.juli.FileHandler.datePattern = yyyy-MM-dd
org.apache.juli.FileHandler.rotatable = true
#org.apache.juli.FileHandler.maxDays = 90

# Standard format
java.util.logging.SimpleFormatter.format = %1$tF %1$tT [%4$s] %2$s - %5$s %6$s%n

############################################################
# Package Specific Levels
############################################################

org.xipki.level = INFO

# loggers = zaxxer
com.zaxxer.level = INFO
