tokentypes = [PKCS11 PKCS12]; each ($tokentypes) {
  tokentype = $it

  keyspecs = [ RSA2048 RSA2048/PSS SECP256R1 SM2P256V1 ED25519 MLDSA44 ]; each ($keyspecs) {
    keyspec = $it

    echo "+++++source qa/camgmt.script    $tokentype $keyspec +++++"
               source qa/camgmt.script    $tokentype $keyspec

    echo "+++++source qa/camgmt.script -l $tokentype $keyspec +++++"
               source qa/camgmt.script -l $tokentype $keyspec
  }

}
