echo "#################################################################"
echo "#                    Initialize Database                        #"
echo "#################################################################"

set CA_DB "${XIPKI_DIR}/etc/ca/database/ca-db.properties"

if "${SQL_FORCE}" eq "yes"
  sql --force --db-conf "${CA_DB}" xipki/sql/ca-init.sql
else
  sql --db-conf "${CA_DB}" xipki/sql/ca-init.sql
fi
